\documentclass[pdftex,11pt,openany]{book}

%\documentclass[11pt,openany]{book}

% команды АК.
\newcommand{\calL}{\mathcal{L}}
\newcommand{\bs}[1]{\boldsymbol{#1}}
\newcommand{\hypo}{\mathcal{H}}
\newcommand{\simhypo}{\ensuremath{\mathrel{\stackrel{\hypo_0}{\sim}}}}

\input{title_bor_utf8_knitr_e}  % no embedfile in _e


% чисто эконометрические сокращения:
\input{emetrix_preamble}


% стандартизация
% эпсилон во временных рядах --- белый шум, а в остальных сюжетах --- остатки, подумать
% транспонирование --- штрих

% задачи типа "воспроизведите тест такой-то ручками в R" -> в тему согласно тесту, а не в доп. задачи по программированию

% идеи задач:
% * Задача на корреляционную матрицу по реальным данным require(quantmod)
% Задача про суеверную Мырли. Можно ли там что-то про se сказать?
% теорему FWL в массы!
% симуляционные задачи на ошибки 1, 2 рода, мощность
% E_t(X) или с указанием сигма-алгебры

% по явному виду процесса определить подходит ли он
% в заданное стохастическое разностное уравнение


% выложить преамбулу


% перегнанные банки:
% 1 ---20

% осталось:
% задача 12, компьютерное про пи (алгоритмы вычисления)
% распределить проверить наличие программистко-сюжетных упражнений


% для отдельной упаковки решений
\ifdef{\JustPlot}{}{\input{prob_and_sol_2chap_e}} % secsolution patch instead of chapter master counter


\title{Эконометрика \\ {\small с Монте-Карло и эконометрессами} \\ в задачах и упражнениях}
\author{Дмитрий Борзых, Борис Демешев}
\date{\today}

\makeindex % команда для создания предметного указателя
\bibliographystyle{plain} % стиль оформления ссылок


\begin{document}

\setcounter{page}{3}

%\maketitle % печатаем заголовок
\tableofcontents




\vspace{30pt}


<<"setup", echo=TRUE, message=FALSE,tidy=FALSE,warning=FALSE>>=
library("knitr")
library("tikzsetup")
library("tikzDevice")
tikzsetup()

library("ggplot2")
library("Hmisc")
library("lmtest")
library("apsrtable")
library("xtable")
library("MASS")
library("car")
library("texreg")
library("memisc")
library("sandwich")

library("econru")

theme_set(theme_bw())

load('pset_data.Rdata')
@



\problemonly


<<child='chapters/050_ml_general.Rnw'>>=
@

\restorechapter
\chapter{Решения и ответы к избранным задачам}
\chaptermark{Избранные решения}

\solutiononly


<<child='chapters/050_ml_general.Rnw'>>=
@

\end{document}
